Resources:

  StaticFiles:
    Type: AWS::S3::Bucket

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          Compress: true
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 400
            ResponseCode: 200
            ResponsePagePath: /404.html
        Enabled: true
        PriceClass: PriceClass_All
        Origins:
          - DomainName: !GetAtt StaticFiles.RegionalDomainName
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Skyworkz website.

  StaticFilesPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticFiles
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: Give CloudFront Access
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub ${StaticFiles.Arn}/*

Outputs:
  staticFilesBucketName:
    Value: !Ref StaticFiles
    Description: Upload your files here using the command 'aws s3 sync --delete ./builtFilesDir s3://yourBucketName'
  websiteDomain:
    Value: !GetAtt CDN.DomainName
